### ISSUE TITLE
Metadata saknas for missing speaker names

### ISSUE THREAD

**Issue by rebeckahw** [humlab-swedeb/swedeb-api#28]
Missing speaker names should be "metadata saknas", now it is just an empty string

(Search for speeches for 1920 to find some examples).

**Comment by roger-mahler** [comment]
PR #57 added a feature that updates values in the speech index using configuration found in `config.yml`. Currently the following configuration is set:

```yaml

display:
  speech_index:
    updates:
      party_abbrev: { "?": "metadata saknas", "X": "partilös" }
      name: { "": "metadata saknas" }

```
